### ISSUE TITLE
Log Viewer Improvements Task List

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#357]
Just writing down some of the things that I've wanted to add to the log viewer and the parsing method to make it more compatible with how people randomize their Pokémon games.

- [x] Parser supports custom names (Pokémon, moves, etc.) instead of hard-coded values
- [x] Parser should read in and use the ability data, instead of relying on the data from the currently loaded game.
- [x] Route menu to check what wild Pokémon are on each route. Perhaps have an actual map shown here
- [ ] Fun stats added to the Misc. tab, stuff like average BST of the elite four.
- [x] A way to "search" the log for something. Something like "where are all the Shedinjas," "which Pokémon have Perish Song," and "what did TRAINER_NAME_HERE have"
- [x] A way to quickly view the log file for the previous seed after resetting (from Extras screen)

**Comment by Aeiiry** [comment]
I would love to help out with any of these if you're open to others' contributions. 
One additional thing I often find myself wishing for in the log is the ability to toggle **only** showing gym TMs for learnable TMs for a given pokemon. Alongside possibly highlighting moves that were STAB or were in the category that the viewed pokemon had the higher stat for (atk or spa)

**Comment by valiant-code** [comment]
One possible idea for the list:
* A way to quickly view the log file for the *previous* seed after resetting

**Comment by UTDZac** [comment]
Custom names and correct ability/type data is now read in as part of #370

**Comment by UTDZac** [comment]
An option/button to view the previous log from the last attempt is now available under the Extras Screen as of #371

**Comment by UTDZac** [comment]
With the recent log viewer changes in v8.1.0, I'm closing this as complete. Most of the functionality for feature ideas from this issue has been added to the Tracker's log viewer now.
